/**
 * Project Wrapper Service
 * Wraps generated React components into complete Next.js deployable projects
 */

export class ProjectWrapper {
  /**
   * Creates a complete Next.js project structure from a single React component
   * @param {string} reactComponent - The generated React component code
   * @param {string} projectName - Name for the project
   * @returns {Object} Complete project file structure
   */
  static createDeployableProject(reactComponent, projectName) {
    // Sanitize project name for npm/Vercel
    const safeName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    
    return {
      'package.json': {
        name: safeName,
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          'next': '14.0.4',
          'react': '18.2.0',
          'react-dom': '18.2.0'
        },
        devDependencies: {
          '@types/node': '20.10.0',
          '@types/react': '18.2.45',
          '@types/react-dom': '18.2.18',
          'autoprefixer': '10.4.16',
          'postcss': '8.4.32',
          'tailwindcss': '3.3.6',
          'typescript': '5.3.3'
        }
      },
      
      'next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: ['images.unsplash.com', 'via.placeholder.com', 'placehold.co'],
    unoptimized: true,
  },
}

module.exports = nextConfig
`,

      'tailwind.config.js': `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
`,

      'postcss.config.js': `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,

      'tsconfig.json': {
        compilerOptions: {
          target: 'es5',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          forceConsistentCasingInFileNames: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          paths: {
            '@/*': ['./*']
          }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
        exclude: ['node_modules']
      },

      'pages/_app.js': `import '../styles/globals.css'

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}
`,

      'pages/_document.js': `import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by WebWeave AI" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
`,

      'pages/index.js': this.wrapComponentForNextJS(reactComponent),

      'styles/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}

* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
}
`,

      '.gitignore': `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`,

      'README.md': `# ${safeName}

This website was generated by **WebWeave AI** - a no-code website generator.

## Getting Started

First, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Deploy on Vercel

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new).

Check out the [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.

---

Generated with ❤️ by [WebWeave AI](https://github.com/dibjyotih/no-code-website-generator)
`,

      'public/favicon.ico': '', // Empty placeholder
      '.vercelignore': `node_modules
.env
.env.local
`,
    };
  }

  /**
   * Wraps a React component to work as a Next.js page
   * @param {string} componentCode - Original React component code
   * @returns {string} Next.js compatible page code
   */
  static wrapComponentForNextJS(componentCode) {
    // Remove any existing imports and exports
    let cleanedCode = componentCode
      .replace(/import\s+.*?from\s+['"].*?['"];?\s*/g, '')
      .replace(/export\s+default\s+/g, '')
      .trim();
    
    // Check if we need useState or useEffect
    const needsUseState = cleanedCode.includes('useState');
    const needsUseEffect = cleanedCode.includes('useEffect');
    
    // Extract component name or use default
    const componentMatch = cleanedCode.match(/(?:function|const)\s+(\w+)/);
    const componentName = componentMatch ? componentMatch[1] : 'GeneratedComponent';
    
    // If it's just JSX without a function wrapper, wrap it
    if (!cleanedCode.includes('function') && !cleanedCode.includes('=>')) {
      cleanedCode = `export default function ${componentName}() {
  return (
    ${cleanedCode}
  );
}`;
    } else {
      // Ensure it has export default
      if (!cleanedCode.includes('export')) {
        // Find the main function/component and add export
        const functionMatch = cleanedCode.match(/((?:function|const)\s+\w+)/);
        if (functionMatch) {
          cleanedCode = cleanedCode.replace(functionMatch[1], `export default ${functionMatch[1]}`);
        } else {
          cleanedCode = `export default ${cleanedCode}`;
        }
      }
    }
    
    // Build imports
    const imports = ["import React from 'react';"];
    if (needsUseState || needsUseEffect) {
      const hooks = [];
      if (needsUseState) hooks.push('useState');
      if (needsUseEffect) hooks.push('useEffect');
      imports.push(`import { ${hooks.join(', ')} } from 'react';`);
    }
    
    return `${imports.join('\n')}

${cleanedCode}
`;
  }

  /**
   * Validates project structure before deployment
   * @param {Object} project - Project file structure
   * @returns {boolean} True if valid
   */
  static validateProject(project) {
    const requiredFiles = [
      'package.json',
      'next.config.js',
      'pages/index.js',
      'pages/_app.js',
      'styles/globals.css'
    ];

    return requiredFiles.every(file => file in project);
  }

  /**
   * Estimates deployment size
   * @param {Object} project - Project file structure
   * @returns {number} Size in KB
   */
  static estimateSize(project) {
    let totalSize = 0;
    for (const [path, content] of Object.entries(project)) {
      const contentString = typeof content === 'string' 
        ? content 
        : JSON.stringify(content);
      totalSize += Buffer.byteLength(contentString, 'utf8');
    }
    return Math.round(totalSize / 1024);
  }
}

export default ProjectWrapper;
